development:
  adapter: postgresql
  encoding: unicode
  database: shs_development
  pool: 5
  username: postgres
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: shs_test
  pool: 5
  username: postgres
  password:
  min_messages: warning
